name = "stock-recambios"
compatibility_date = "2024-01-01"

# Pages: directorio de salida est√°tica (HTML, CSS, JS)
pages_build_output_dir = "public"

# Base de datos D1
[[d1_databases]]
binding = "DB"
database_name = "stock-db"
database_id = "a4662b08-e159-473b-9e87-e92cd77d3bca"
